name: "Terraform Apply"
on:
  push:
    branches:
      - main
env:
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prep the required secrets
        run: |
          echo "${{ vars.TEST_VARIABLE }}" > test_var
          cat test_var
          echo "${{ secrets.BACKEND }}" > backend
          echo "${{ secrets.OCI_PEM }}" > oci.pem
          echo "${{ secrets.TERRAFORM_TFVARS }}" > terraform.tfvars
      - name: Restore cached Terraform plan
        uses: actions/cache/restore@v4
        with:
          path: |
            plan.out
          key: terraform_plan-${{github.run_id}}-${{github.run_attempt}}
      - name: Get tfer
        run: |
          wget https://raw.githubusercontent.com/RihardsT/tfer/refs/heads/main/tfer
          chmod +x tfer
      - name: Terraform Init
        run: ./tfer init -backend-config=../backend
      - name: Terraform Apply
        run: ./tfer apply plan.out
