name: "Terraform Plan"
on:
  push:
    branches: [ "main" ]
  pull_request:

outputs:
  change:
    description: "Parsed Terraform plan changes"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prep the required secrets
        run: |
          echo "${{ vars.TEST_VARIABLE }}" > test_var
          cat test_var
          echo ${PWD}
          echo ~
          echo "${{ secrets.BACKEND }}" | base64 -d > backend
          echo "${{ secrets.OCI_PEM }}" > oci.pem
          echo "${{ secrets.TERRAFORM_TFVARS }}" | base64 -d > terraform.tfvars
      - name: Get tfer
        run: |
          wget https://raw.githubusercontent.com/RihardsT/tfer/refs/heads/main/tfer
          chmod +x tfer
      - name: Terraform Init
        run: terraform init -backend-config=backend
      - name: Terraform Plan
        run: ./tfer plan -out=../plan.out
      - name: Cache Terraform Plan
        uses: actions/cache/save@v4
        with:
          path: |
            plan.out
          key: terraform_plan-${{github.run_id}}-${{github.run_attempt}}
      ##### 
      - name: plan.out as json
        id: plan-output
        run:
          terraform show -json plan.out > plan.json
          changes=$(jq -r '.resource_changes[] | select(.change.actions[] != "no-op") | "\(.change.actions[]) = \(.address)"' plan.json)
          echo "::set-output name=change::$changes"
      #####
      - name: Update PR
        uses: actions/github-script@v6
        id: plan-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Cloud Output')
            });
            const output = `#### Terraform Plan Output
               \`\`\`
               Plan changes: ${{ steps.plan-output.outputs.change }}
               \`\`\`
               `;
            // 3. Delete previous comment so PR timeline makes sense
            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
